// <auto-generated />
using System;
using Acxess.Catalog.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Acxess.Catalog.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(CatalogModuleContext))]
    [Migration("20251229175048_InitCatalog")]
    partial class InitCatalog
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("Catalog")
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Acxess.Catalog.Domain.Entities.AccessTier", b =>
                {
                    b.Property<int>("AccessTierId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AccessTierId"));

                    b.Property<string>("Description")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<int>("TenantId")
                        .HasColumnType("int");

                    b.HasKey("AccessTierId");

                    b.HasIndex("TenantId");

                    b.ToTable("AccessTiers", "Catalog");
                });

            modelBuilder.Entity("Acxess.Catalog.Domain.Entities.AddOn", b =>
                {
                    b.Property<int>("AddOnId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AddOnId"));

                    b.Property<string>("AddOnKey")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Price")
                        .IsRequired()
                        .HasPrecision(10, 2)
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("ShowInCheckout")
                        .HasColumnType("bit");

                    b.Property<int>("TenantId")
                        .HasColumnType("int");

                    b.HasKey("AddOnId");

                    b.HasIndex("TenantId");

                    b.HasIndex("TenantId", "AddOnKey")
                        .IsUnique();

                    b.ToTable("AddOns", "Catalog");
                });

            modelBuilder.Entity("Acxess.Catalog.Domain.Entities.PlanAccessTiers", b =>
                {
                    b.Property<int>("PlanAccessTierId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PlanAccessTierId"));

                    b.Property<int>("AccessTierId")
                        .HasColumnType("int");

                    b.Property<int>("SellingPlanId")
                        .HasColumnType("int");

                    b.HasKey("PlanAccessTierId");

                    b.ToTable("PlanAccessTiers", "Catalog");
                });

            modelBuilder.Entity("Acxess.Catalog.Domain.Entities.SellingPlan", b =>
                {
                    b.Property<int>("SellingPlanId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SellingPlanId"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<int>("CreatedByUser")
                        .HasColumnType("int");

                    b.Property<byte>("DurationInValue")
                        .HasColumnType("tinyint");

                    b.Property<int>("DurationUnit")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Price")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("TenantId")
                        .HasColumnType("int");

                    b.Property<int>("TotalMembers")
                        .HasColumnType("int");

                    b.HasKey("SellingPlanId");

                    b.HasIndex("CreatedByUser");

                    b.HasIndex("SellingPlanId");

                    b.HasIndex("TenantId");

                    b.ToTable("SellingPlans", "Catalog");
                });
#pragma warning restore 612, 618
        }
    }
}
